name: Deploy Server Bot

on:
  workflow_dispatch:  # ম্যানুয়ালি চালানোর জন্য

jobs:
  run_with_timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # ১ ঘণ্টার টাইমআউট

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (Latest Version)
        uses: actions/setup-node@v3
        with:
          node-version: 'node'  # সর্বশেষ Node.js সংস্করণ (latest version)

      - name: Install npm libraries
        run: npm install  # NPM লাইব্রেরি ইনস্টল

      - name: Run the application
        id: run_app  # স্টেপের ID
        run: node index.js  # অ্যাপ্লিকেশন চালানো

      - name: Set job to restart on failure or timeout
        if: ${{ failure() || cancelled() }}  # যদি জবটি ব্যর্থ হয় বা টাইমআউট হয়
        run: echo "::set-output name=restart_job::true"  # আউটপুট সেট করা হচ্ছে

      - name: Set job not to restart on success
        if: ${{ success() }}  # সফল হলে
        run: echo "::set-output name=restart_job::false"  # আউটপুট false করা হচ্ছে

  restart_job:
    runs-on: ubuntu-latest
    needs: run_with_timeout
    if: ${{ needs.run_with_timeout.outputs.restart_job == 'true' }}  # Output যাচাই করা হচ্ছে
    steps:
      - name: Restart the job
        run: |
          echo "Restarting the job..."
          # পুনরায় শুরু করার জন্য এখানে প্রয়োজনীয় কাজগুলো করা হবে
