name: Deploy Server Bot

on:
  workflow_dispatch:  # ম্যানুয়ালভাবে শুরু করার জন্য

jobs:
  run_with_timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # ১ ঘণ্টার টাইমআউট

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Node.js সংস্করণ

      - name: Install npm libraries
        run: npm install  # NPM লাইব্রেরি ইনস্টল করবে

      - name: Run the application
        run: node index.js  # অ্যাপ্লিকেশন চালাবে

      - name: Notify Timeout
        if: ${{ failure() || cancelled() }}  # যদি জবটি টাইমআউট বা ব্যর্থ হয়
        run: |
          echo "Job timed out. Restarting the job..."
          echo "RESTART_JOB=true" >> $GITHUB_ENV  # GITHUB_ENV এর মাধ্যমে RESTART_JOB সেট করা হচ্ছে

  restart_job:
    runs-on: ubuntu-latest
    needs: run_with_timeout
    if: ${{ steps['run_with_timeout'].outputs.RESTART_JOB == 'true' }}  # RESTART_JOB চেক করা হচ্ছে
    steps:
      - name: Restart the job
        run: |
          echo "Restarting the job..."
