name: Deploy Server Bot

on:
  workflow_dispatch:  # ম্যানুয়ালি চালু করার জন্য

jobs:
  run_with_timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # ১ ঘণ্টার টাইমআউট

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Node.js সংস্করণ

      - name: Install npm libraries
        run: npm install  # NPM লাইব্রেরি ইনস্টল

      - name: Run the application
        id: run_app  # ID সেট করা
        run: node index.js  # অ্যাপ্লিকেশন চালানো

      - name: Notify Timeout
        if: ${{ failure() || cancelled() }}  # যদি জবটি টাইমআউট হয়
        run: |
          echo "Job timed out. Restarting the job..."
        outputs:
          restart_job: true  # Output এ restart_job সেট করা

      - name: Set output on success
        if: ${{ success() }}  # সফল হলে output false করে দেওয়া
        run: echo "RESTART_JOB=false" >> $GITHUB_ENV
        outputs:
          restart_job: false  # Output এ restart_job false করে দেওয়া হচ্ছে

  restart_job:
    runs-on: ubuntu-latest
    needs: run_with_timeout
    if: ${{ needs.run_with_timeout.outputs.restart_job == 'true' }}  # Output থেকে restart_job যাচাই করা হচ্ছে
    steps:
      - name: Restart the job
        run: |
          echo "Restarting the job..."
          # এখানে পুনরায় শুরু করার জন্য কাজগুলি করা হবে
